/* This file was generated by param.py.  Do not edit. */

#ifndef PATSOLVE_PARAM_H
#define PATSOLVE_PARAM_H

#include "fcs_pats_xy_param.h"

extern const fcs_pats_xy_param_t freecell_solver_pats__x_y_params_preset[];

#define FC_SOLVE_PATS__PARAM_PRESET__FreecellSpeed 0
#define FC_SOLVE_PATS__PARAM_PRESET__FreecellBest 1
#define FC_SOLVE_PATS__PARAM_PRESET__FreecellBestA 2
#define FC_SOLVE_PATS__PARAM_PRESET__SeahavenBest 3
#define FC_SOLVE_PATS__PARAM_PRESET__SeahavenBestA 4
#define FC_SOLVE_PATS__PARAM_PRESET__SeahavenSpeed 5
#define FC_SOLVE_PATS__PARAM_PRESET__SeahavenKing 6
#define FC_SOLVE_PATS__PARAM_PRESET__SeahavenKingSpeed 7
#define FC_SOLVE_PATS__PARAM_PRESET__LastParam 7

#endif /* PATSOLVE_PARAM_H */
