/* Copyright (c) 2002 Tom Holroyd
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */
/* This file was generated by param.py.  Do not edit. */

#include "param.h"

XYparam_t XYparam[] = {
 {{ 4, 1, 8, -1, 7, 11, 4, 2, 2, 1, 2, }, { 0.0032, 0.32, -3.0, }},
 {{ 3, 4, 7, -4, -2, 1, 0, -4, 4, -1, 1, }, { -0.0008, 0.14, -1.0, }},
 {{ 2, 4, 7, -2, -2, 1, 0, -5, 4, -1, 1, }, { -0.0024, 0.22, 0.0, }},
 {{ 1, 3, 2, 2, 2, 3, -2, 2, 2, -1, 1, }, { 0.0008, 0.02, -4.0, }},
 {{ 2, 2, 4, 0, 1, 2, 1, 1, 2, -1, 1, }, { -0.0008, 0.18, -5.0, }},
 {{ 1, 1, 6, -2, -1, -2, -2, -3, 0, -1, 2, }, { 0.0, 0.08, 2.0, }},
 {{ 2, 6, 2, 0, -5, -9, -5, -11, 3, 1, 1, }, { -0.0056, 0.42, -5.0, }},
 {{ 2, 2, 5, -3, -1, -3, -3, -4, 4, 1, 3, }, { -0.0032, 0.24, 2.0, }},
};
