addons:
    apt:
        packages:
            - build-essential
            - cmake
            - cmake-data
            - cpanminus
            - libperl-dev
            - ninja-build
            - perl
            - valgrind
            - xz-utils
            - zip
os: linux
dist: bionic
install:
    - sudo cpanm --notest autodie strict warnings Cwd Env::Path File::Basename File::Copy File::Path File::Spec File::Which Getopt::Long IO::All Moo Path::Tiny Perl::Tidy Test::Differences Test::More Test::PerlTidy Test::TrailingSpace Test::Trap
    - git clone https://github.com/shlomif/fc-solve
    - "git clone https://github.com/shlomif/rinutils && cd rinutils && mkdir b && cd b && cmake -DWITH_TEST_SUITE=OFF .. && make && sudo make install && cd ../.. && rm -fr rinutils"
perl:
    - "5.26"
python:
    - "3.5"
script: "mkdir build && cd build && cmake -DFC_SOLVE_SRC_PATH=\"$(pwd)/../fc-solve/fc-solve/source/\" ../patsolve && make && make check"
